name: nothing_gyro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+3

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  nothing_glyph_interface: ^0.0.4
  sensors_plus: ^5.0.1
  # tilt: ^0.0.2
  flutter_tilt: 3.0.1
  flutter_launcher_icons: ^0.13.1

# dependency_overrides:
#   sensors_plus: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/NP1.jpg
    - assets/images/NP2.jpg
    - assets/images/NPfront.png

  fonts:
    - family: Ndot
      fonts:
        - asset: assets/fonts/nothing-font-5x7.ttf
    - family: NType82
      fonts:
        - asset: assets\fonts\NType82-Regular.otf
    - family: NType82Mono
      fonts:
        - asset: assets\fonts\NType82Mono-Regular.otf
        
  

 